#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

out_dir="data/docker-smoke"
mkdir -p "$out_dir" logs map_bundles transfer

echo "[1/3] Building Docker image"
./scripts/pi/build_docker.sh

echo "[2/3] Generating synthetic image pair inside Docker"
./scripts/pi/run_docker.sh bash -lc \
  "vision-nav-generate-synthetic-pair --output-dir /data/docker-smoke"

cat >"$out_dir/manifest.json" <<EOF
{
  "bundle_id": "docker-smoke-synthetic",
  "description": "Synthetic single-image bundle generated by smoke_test_docker.sh",
  "coordinate_frame": "simple_local_tangent",
  "orthophoto": {
    "path": "synthetic_map.png",
    "origin_lat": 40.0,
    "origin_lon": -75.0,
    "origin_pixel_x": 0.0,
    "origin_pixel_y": 0.0,
    "gsd_m": 0.2,
    "rotation_deg": 0.0
  },
  "features": {
    "path": "synthetic_map_features.npz",
    "method": "orb",
    "max_features": 3000
  }
}
EOF

echo "[3/3] Running feature-map build and match inside Docker"
./scripts/pi/run_docker.sh bash -lc "
set -euo pipefail
vision-nav-build-bundle \
  --bundle /data/docker-smoke \
  --metadata-json /data/docker-smoke/synthetic_map_features.json

vision-nav-match-bundle-frame \
  --bundle /data/docker-smoke \
  --frame /data/docker-smoke/synthetic_query.png \
  --min-inliers 8 \
  --ratio 0.85 \
  --viz /data/docker-smoke/synthetic_match_debug.jpg \
  | tee /data/docker-smoke/synthetic_match_result.json
"

echo
echo "Docker smoke outputs written to: $repo_root/$out_dir"
