#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
venv_python="${VISION_NAV_PYTHON:-$HOME/drone_vision_nav_venv/bin/python}"
out_dir="${VISION_NAV_SMOKE_DIR:-$HOME/DroneTransfer/outgoing/vision-smoke}"

if [[ ! -x "$venv_python" ]]; then
  echo "Missing Python venv: $venv_python" >&2
  echo "Run ./scripts/pi/bootstrap_pi5.sh first, then reboot." >&2
  exit 1
fi

mkdir -p "$out_dir"

echo "[1/3] Capturing camera frame if camera tools are available"
if command -v rpicam-still >/dev/null 2>&1 || command -v libcamera-still >/dev/null 2>&1; then
  PYTHONPATH="$repo_root/src" "$venv_python" -m vision_nav.capture_frame \
    --output "$out_dir/global_shutter_capture.jpg" \
    --width 1456 \
    --height 1088 \
    --timeout-ms 1000
else
  echo "[WARN] No rpicam-still/libcamera-still command found; skipping camera capture."
fi

echo "[2/3] Creating synthetic map/query images"
PYTHONPATH="$repo_root/src" "$venv_python" -m vision_nav.generate_synthetic_pair \
  --output-dir "$out_dir"

cat >"$out_dir/manifest.json" <<EOF
{
  "bundle_id": "pi-smoke-synthetic",
  "description": "Synthetic single-image bundle generated by smoke_test_vision.sh",
  "coordinate_frame": "simple_local_tangent",
  "orthophoto": {
    "path": "synthetic_map.png",
    "origin_lat": 40.0,
    "origin_lon": -75.0,
    "origin_pixel_x": 0.0,
    "origin_pixel_y": 0.0,
    "gsd_m": 0.2,
    "rotation_deg": 0.0
  },
  "features": {
    "path": "synthetic_map_features.npz",
    "method": "orb",
    "max_features": 3000
  }
}
EOF

echo "[3/3] Building feature index and matching synthetic frame"
PYTHONPATH="$repo_root/src" "$venv_python" -m vision_nav.build_map_bundle \
  --bundle "$out_dir" \
  --metadata-json "$out_dir/synthetic_map_features.json"

PYTHONPATH="$repo_root/src" "$venv_python" -m vision_nav.match_bundle_frame \
  --bundle "$out_dir" \
  --frame "$out_dir/synthetic_query.png" \
  --min-inliers 8 \
  --ratio 0.85 \
  --viz "$out_dir/synthetic_match_debug.jpg" \
  | tee "$out_dir/synthetic_match_result.json"

echo
echo "Smoke outputs written to: $out_dir"
